import { generateText } from "ai";
import { getAIModel } from "@/utils/ai_providers";
import { getOutlinePrompt } from "@/utils/prompts";
import { parseOutlineToChapterInputs } from "@/utils/agent/outline";
import { createBookOutline } from "@/app/api/chat/actions";
import { saveChapterContent } from "@/app/api/chapter/actions";
import { getI18n } from "@/utils/i18n/server";
import { getPrisma } from "@/utils/prisma";
import { Book, Chapter } from "@prisma/client";

type RunLogEntry = { ts: string; step: string; message: string };

async function updateRun(bookId: string, step: string, message: string) {
  const prisma = getPrisma();
  const run = await prisma.agentRun.findUnique({ where: { bookId } });
  const log = (run?.log as RunLogEntry[] | undefined) ?? [];
  log.push({ ts: new Date().toISOString(), step, message });
  await prisma.agentRun.update({
    where: { bookId },
    data: { currentStep: step, log },
  });
}

export async function generateChapterContent(
  chapterId: number,
  model: string,
  book: Book & { chapters: Chapter[] }
) {
  const [provider, modelName] = model.split("/");
  const i18n = getI18n(book.language);
  // The specific chapter we are writing — without injecting it, the model only
  // sees the whole outline and produces identical content for every chapter.
  const target = book.chapters.find((c) => c.id === chapterId) ?? book.chapters[0];
  const systemPrompt = `${i18n.t("bookChapterPrompt")}
      # General Instructions
        ${book.prompt}
      # Outline
        ${JSON.stringify(book.chapters)}
      # Chapter to write now
        Title: ${target?.title ?? ""}
        Description: ${target?.description ?? ""}
      # Write with Language: ${book.language}
    `;
  const result = await generateText({
    model: getAIModel(provider, modelName),
    system: systemPrompt,
    messages: [{
      role: "user",
      content: `请撰写以下章节的内容：\n标题：${target?.title ?? ""}\n简介：${target?.description ?? ""}`,
    }],
    temperature: 0,
  });
  await saveChapterContent(chapterId, result.text);
  return result.text;
}

// Single-process, fire-and-forget orchestrator.
// NOTE: production should move this to a queue/worker.
export async function runAutonomousBook(bookId: string) {
  const prisma = getPrisma();
  const run = await prisma.agentRun.findUnique({ where: { bookId } });
  if (!run) return;

  try {
    const book = await prisma.book.findUnique({
      where: { id: bookId },
      include: { chapters: { orderBy: { position: "asc" } } },
    });
    if (!book) throw new Error("Book not found");

    // PROMPT stage: book.prompt already generated by createBook
    await updateRun(bookId, "PROMPT", "Standard prompt ready");

    // OUTLINE stage
    await updateRun(bookId, "OUTLINE", "Generating outline...");
    const [pProvider, pModel] = book.model.split("/");
    const outlineResult = await generateText({
      model: getAIModel(pProvider, pModel),
      system: getOutlinePrompt(book),
      messages: [{ role: "user", content: "请按照以上要求生成书籍大纲。" }],
      temperature: 0,
    });
    const chapterInputs = parseOutlineToChapterInputs(outlineResult.text);
    await createBookOutline(bookId, chapterInputs);

    // CHAPTER stage
    // leafChapters is ordered by position asc. createBookOutline inserts
    // via createMany in array order, so position order == autoincrement id
    // order; saveChapterContent advances currentChapterId by id, staying in sync.
    const leafChapters = await prisma.chapter.findMany({
      where: { bookId, leaf: true },
      orderBy: { position: "asc" },
    });
    for (let i = 0; i < leafChapters.length; i++) {
      await updateRun(
        bookId,
        `CHAPTER:${i + 1}/${leafChapters.length}`,
        `Writing chapter: ${leafChapters[i].title}`
      );
      await generateChapterContent(leafChapters[i].id, book.model, {
        ...book,
        chapters: leafChapters,
      });
    }

    await prisma.book.update({ where: { id: bookId }, data: { step: "COMPLETE" } });
    await prisma.agentRun.update({
      where: { bookId },
      data: { status: "DONE", currentStep: "COMPLETE" },
    });
  } catch (e: any) {
    await prisma.agentRun.update({
      where: { bookId },
      data: { status: "FAILED", error: e?.message ?? "Unknown error" },
    });
  }
}
